### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by 4kxz** [RookieOne/react-alt-github-example#1]
I followed the steps in the readme but I had to install vinyl-source-stream before it worked. This was in Linux.

It's a good example of a basic simple app, thanks for sharing it.

**Comment by michaelBenin** [comment]
Also ran into this on mac:

```
NYNYMBENINOXM:penton-properties michael.benin$ gulp
module.js:338
    throw err;
          ^
Error: Cannot find module 'vinyl-source-stream'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/michael.benin/Desktop/penton-properties/gulpFile.js:8:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

Thanks @Alkxzv - one of us should make a PR :)
